### ISSUE TITLE
Scala examples?

### ISSUE THREAD

**Issue by pnf** [JetBrains/capture-points#3]
Would it be possible to add example source files that demonstrate the capture points?
After loading the `scala.xml` configuration, I tried to test it with something like
```.scala  
  import scala.concurrent.ExecutionContext.Implicits.global
  def bar = {
    println("hi")  // set breakpoint here
    1
  }
  def foo = {
    val f = Future { bar  }
    f.onComplete {
      case Success(i) => i + 1
      case Failure(t) => throw (t)
    }
  }
  println(foo)

```
but, with a breakpoint set at the `println`, I see exactly the same stack with the capture enabled and not.  In particular, there is no indication of `foo` on the stack.  By contrast, the Java equivalent with `CompletableFuture` shows the captured stack more or less as in the blog post.

**Comment by niktrop** [comment]
Your example doesn't work because `Function0` has specialized methods for primitive types. You may either change your `bar` method to return `AnyRef` or add more insertion points:
https://github.com/JetBrains/capture-points/commit/9f0481e17cd23b8dec62e4ed153a185aeb6b5eb5

**Comment by mwisnicki** [comment]
I've imported everything but it still doesn't work. All I get is a lot of
```
Unable to evaluate insert key expression: Cannot find local variable '$this0'
```
And everything is super slow. I'm on Scala 2.11 though

**Comment by niktrop** [comment]
@mwisnicki Can you give an example? I've tried the one above with 2.11.11 and had no issues.

**Comment by pnf** [comment]
@niktrop Thanks for the updated scala config with specialization.  I still think, per the subject of this issue, that example source files would be helpful.
@mwisnicki The example I gave above works for me, though I've only tried in 2.12.

**Comment by niktrop** [comment]
I've added examples for scala Futures and akka Actors.
https://github.com/JetBrains/capture-points/tree/master/examples

**Comment by pnf** [comment]
Thanks.  This looks great.  I have some other questions, but I'll ask them in another issue.
