### ISSUE TITLE
DAG?

### ISSUE THREAD

**Issue by pnf** [JetBrains/capture-points#5]
I'm pretty sure I know the answer to this one, but I want to confirm.
It seems that there is no one "correct"  pseudo-stack to capture, even for very simple async use cases.  In my previous issue #4, it would be equally reasonable to expect to see either the `launch` or the `get` call on the stack; moreover, there could be multiple threads waiting for `get`.  
My understanding is that there's no way at present to accommodate multiple parentage in the async stack, because stacks are stored in a map.
I experimented with multiple capture methods for the same key, and it appears that the last one "wins," i.e. overwrites whatever was in the map previously.  This is the expected behavior, right?

**Comment by gorrus** [comment]
True, for now one key = one stack
